spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testauthdb?useSSL=false
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: facebook-client-id
            client-secret: facebook-client-secret
          github:
            client-id: github-client-id
            client-secret: github-client-secret
          google:
            client-id: google-client-id
            client-secret: google-client-secret